/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIstas.Administracion;

import AccesoADatos.HabitacionData;
import AccesoADatos.HuespedData;
import AccesoADatos.ReservaData;
import VIstas.AdministracionView;
import entidades.Habitacion;
import entidades.Huesped;
import entidades.Reserva;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Rodri
 */
public class PanelCheckInOut extends javax.swing.JPanel {

    private Reserva reserva;
    private HabitacionData habData;
    private ReservaData resData;
    private Habitacion habitacion;
    private Huesped huesped;

    private PanelAdminHabitaciones panelAdmin;
    private AdministracionView ventana;

    public PanelCheckInOut(AdministracionView ventana, PanelAdminHabitaciones panelAdmin,
            Reserva reserva, HabitacionData habData, ReservaData resData) {
        this.reserva = reserva;
        this.habData = habData;
        this.resData = resData;
        this.ventana = ventana;
        this.panelAdmin = panelAdmin;
        initComponents();
        this.setVisible(false);
        cargarComboNumeros();
        cargarDatosReserva();
        cargarDatosHabitacion();
        cargarDatosHuesped();
    }

    public PanelCheckInOut(AdministracionView ventana, PanelAdminHabitaciones panelAdmin, HabitacionData habData, ReservaData resData) {
        this.habData = habData;
        this.resData = resData;
        this.ventana = ventana;
        this.panelAdmin = panelAdmin;
        initComponents();
        this.setVisible(false);
        cargarComboNumeros();
    }


    /**
     * Creates new form panelAdminHabitaciones
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelOpciones = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        labelChekIn = new javax.swing.JLabel();
        comboBoxNumeroReserva = new javax.swing.JComboBox<>();
        labelNumReserva = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelAtributos = new javax.swing.JPanel();
        textFieldPisoHab = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelHabitacion = new javax.swing.JLabel();
        labelNumeroHab = new javax.swing.JLabel();
        labelTipoHab = new javax.swing.JLabel();
        textFieldTipoHab = new javax.swing.JTextField();
        labelPisoHab = new javax.swing.JLabel();
        textFieldNumeroHab = new javax.swing.JTextField();
        panelAtributos1 = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        textFieldDomicilio = new javax.swing.JTextField();
        labelHuesped = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelDocumento = new javax.swing.JLabel();
        textFieldDni = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelEstadia = new javax.swing.JLabel();
        textFieldFechaIn = new javax.swing.JTextField();
        labelFechaIn = new javax.swing.JLabel();
        labelFechaOut = new javax.swing.JLabel();
        textFieldFechaOut = new javax.swing.JTextField();
        textFieldValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonLimpiar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(27, 118, 134));
        setPreferredSize(new java.awt.Dimension(984, 581));

        panelOpciones.setOpaque(false);

        botonVolver.setBackground(new java.awt.Color(176, 184, 157));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/undo.png"))); // NOI18N
        botonVolver.setContentAreaFilled(false);
        botonVolver.setOpaque(true);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        labelChekIn.setBackground(new java.awt.Color(176, 184, 157));
        labelChekIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelChekIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChekIn.setText("CHECK IN");
        labelChekIn.setOpaque(true);
        labelChekIn.setPreferredSize(new java.awt.Dimension(300, 30));

        comboBoxNumeroReserva.setBackground(new java.awt.Color(176, 184, 157));
        comboBoxNumeroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNumeroReservaActionPerformed(evt);
            }
        });

        labelNumReserva.setBackground(new java.awt.Color(176, 184, 157));
        labelNumReserva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNumReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumReserva.setText("NÚMERO DE RESERVA");
        labelNumReserva.setOpaque(true);

        botonActualizar.setBackground(new java.awt.Color(176, 184, 157));
        botonActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cached.png"))); // NOI18N
        botonActualizar.setContentAreaFilled(false);
        botonActualizar.setOpaque(true);
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver)
                .addGap(184, 184, 184)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(labelNumReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxNumeroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelChekIn, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizar)
                .addGap(23, 23, 23))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxNumeroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelChekIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setOpaque(false);

        panelAtributos.setOpaque(false);

        textFieldPisoHab.setEditable(false);
        textFieldPisoHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldPisoHab.setPreferredSize(new java.awt.Dimension(80, 28));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelHabitacion.setBackground(new java.awt.Color(176, 184, 157));
        labelHabitacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHabitacion.setText(" INFORMACIÓN   HABITACIÓN");
        labelHabitacion.setOpaque(true);
        labelHabitacion.setPreferredSize(new java.awt.Dimension(300, 30));

        labelNumeroHab.setBackground(new java.awt.Color(176, 184, 157));
        labelNumeroHab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNumeroHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumeroHab.setText("NÚMERO");
        labelNumeroHab.setOpaque(true);

        labelTipoHab.setBackground(new java.awt.Color(176, 184, 157));
        labelTipoHab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTipoHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoHab.setText("TIPO");
        labelTipoHab.setOpaque(true);

        textFieldTipoHab.setEditable(false);
        textFieldTipoHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTipoHab.setPreferredSize(new java.awt.Dimension(80, 28));

        labelPisoHab.setBackground(new java.awt.Color(176, 184, 157));
        labelPisoHab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPisoHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPisoHab.setText("PISO");
        labelPisoHab.setOpaque(true);

        textFieldNumeroHab.setEditable(false);
        textFieldNumeroHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNumeroHab.setPreferredSize(new java.awt.Dimension(80, 28));

        javax.swing.GroupLayout panelAtributosLayout = new javax.swing.GroupLayout(panelAtributos);
        panelAtributos.setLayout(panelAtributosLayout);
        panelAtributosLayout.setHorizontalGroup(
            panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtributosLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel6))
                    .addGroup(panelAtributosLayout.createSequentialGroup()
                        .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelTipoHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPisoHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNumeroHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelHabitacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNumeroHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(textFieldPisoHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAtributosLayout.setVerticalGroup(
            panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtributosLayout.createSequentialGroup()
                .addComponent(labelHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroHab, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNumeroHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtributosLayout.createSequentialGroup()
                        .addComponent(labelPisoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtributosLayout.createSequentialGroup()
                        .addComponent(textFieldPisoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldTipoHab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(labelTipoHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        panelAtributos1.setOpaque(false);

        labelEmail.setBackground(new java.awt.Color(176, 184, 157));
        labelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmail.setText("EMAIL");
        labelEmail.setOpaque(true);

        labelDomicilio.setBackground(new java.awt.Color(176, 184, 157));
        labelDomicilio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDomicilio.setText("DOMICILIO");
        labelDomicilio.setOpaque(true);

        textFieldDomicilio.setEditable(false);
        textFieldDomicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDomicilio.setPreferredSize(new java.awt.Dimension(80, 28));

        labelHuesped.setBackground(new java.awt.Color(176, 184, 157));
        labelHuesped.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHuesped.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHuesped.setText("DATOS  DEL  HUESPED");
        labelHuesped.setOpaque(true);
        labelHuesped.setPreferredSize(new java.awt.Dimension(300, 30));

        labelNombre.setBackground(new java.awt.Color(176, 184, 157));
        labelNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("NOMBRE");
        labelNombre.setOpaque(true);

        textFieldNombre.setEditable(false);
        textFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNombre.setPreferredSize(new java.awt.Dimension(80, 28));

        labelDocumento.setBackground(new java.awt.Color(176, 184, 157));
        labelDocumento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDocumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDocumento.setText("N° DOCUMENTO");
        labelDocumento.setOpaque(true);

        textFieldDni.setEditable(false);
        textFieldDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDni.setPreferredSize(new java.awt.Dimension(80, 28));
        textFieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDniKeyReleased(evt);
            }
        });

        labelTelefono.setBackground(new java.awt.Color(176, 184, 157));
        labelTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefono.setText("TELÉFONO");
        labelTelefono.setOpaque(true);

        textFieldEmail.setEditable(false);
        textFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEmail.setPreferredSize(new java.awt.Dimension(80, 28));

        textFieldTelefono.setEditable(false);
        textFieldTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTelefono.setPreferredSize(new java.awt.Dimension(80, 28));

        javax.swing.GroupLayout panelAtributos1Layout = new javax.swing.GroupLayout(panelAtributos1);
        panelAtributos1.setLayout(panelAtributos1Layout);
        panelAtributos1Layout.setHorizontalGroup(
            panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtributos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtributos1Layout.createSequentialGroup()
                            .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(textFieldDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtributos1Layout.createSequentialGroup()
                            .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(textFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtributos1Layout.createSequentialGroup()
                            .addComponent(labelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(textFieldDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAtributos1Layout.setVerticalGroup(
            panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtributos1Layout.createSequentialGroup()
                .addComponent(labelHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtributos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonGuardar.setBackground(new java.awt.Color(176, 184, 157));
        botonGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jPanel4.setOpaque(false);

        labelEstadia.setBackground(new java.awt.Color(176, 184, 157));
        labelEstadia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelEstadia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstadia.setText("ESTADÍA");
        labelEstadia.setOpaque(true);
        labelEstadia.setPreferredSize(new java.awt.Dimension(300, 30));

        textFieldFechaIn.setEditable(false);
        textFieldFechaIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldFechaIn.setPreferredSize(new java.awt.Dimension(80, 28));

        labelFechaIn.setBackground(new java.awt.Color(176, 184, 157));
        labelFechaIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFechaIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaIn.setText("FECHA ENTRADA");
        labelFechaIn.setOpaque(true);

        labelFechaOut.setBackground(new java.awt.Color(176, 184, 157));
        labelFechaOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFechaOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaOut.setText("FECHA SALIDA");
        labelFechaOut.setOpaque(true);

        textFieldFechaOut.setEditable(false);
        textFieldFechaOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldFechaOut.setPreferredSize(new java.awt.Dimension(80, 28));

        textFieldValor.setEditable(false);
        textFieldValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldValor.setPreferredSize(new java.awt.Dimension(80, 28));

        labelValor.setBackground(new java.awt.Color(176, 184, 157));
        labelValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValor.setText("VALOR $");
        labelValor.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFechaOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFechaIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textFieldFechaOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldFechaIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(textFieldFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botonLimpiar.setBackground(new java.awt.Color(176, 184, 157));
        botonLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelAtributos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonLimpiar))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelAtributos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        volverAlMenu();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void comboBoxNumeroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNumeroReservaActionPerformed
        try {
            System.out.println("try");
            if (comboBoxNumeroReserva.getSelectedIndex() != 0) {
                System.out.println("entro al combo");
                int idReserva = Integer.parseInt(comboBoxNumeroReserva.getSelectedItem().toString());
                System.out.println("paso el parseint");
                reserva = resData.buscarReservaId(idReserva);
                cargarDatosReserva();
                cargarDatosHabitacion();
                cargarDatosHuesped();
                botonGuardar.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            limpiarCampos();
        } catch (NullPointerException e) {
            // JOptionPane.showMessageDialog(this, "NullPointer");
            limpiarCampos();
        }

    }//GEN-LAST:event_comboBoxNumeroReservaActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (labelChekIn.getText().equals("CHECK IN")) {
            habData.ocuparHabitacion(habitacion.getIdHabitacion());
        } else {
            habData.liberarHabitacion(habitacion.getIdHabitacion());
        }
        resData.modificarReserva(reserva);
        limpiarCampos();
        cargarComboNumeros();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textFieldDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDniKeyReleased

        if (textFieldDni.getText().equals("dni")) {

        }
    }//GEN-LAST:event_textFieldDniKeyReleased

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        cargarComboNumeros();
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxNumeroReserva;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelChekIn;
    private javax.swing.JLabel labelDocumento;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstadia;
    private javax.swing.JLabel labelFechaIn;
    private javax.swing.JLabel labelFechaOut;
    private javax.swing.JLabel labelHabitacion;
    private javax.swing.JLabel labelHuesped;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumReserva;
    private javax.swing.JLabel labelNumeroHab;
    private javax.swing.JLabel labelPisoHab;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipoHab;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel panelAtributos;
    private javax.swing.JPanel panelAtributos1;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextField textFieldDni;
    private javax.swing.JTextField textFieldDomicilio;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFechaIn;
    private javax.swing.JTextField textFieldFechaOut;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNumeroHab;
    private javax.swing.JTextField textFieldPisoHab;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JTextField textFieldTipoHab;
    private javax.swing.JTextField textFieldValor;
    // End of variables declaration//GEN-END:variables

    private void volverAlMenu() {
        ventana.mostrarPanelContenido(panelAdmin, null);
        panelAdmin.filtrarHabitaciones();
        this.setVisible(false);
    }

    public void cargarComboNumeros() {
        comboBoxNumeroReserva.removeAllItems();
        comboBoxNumeroReserva.addItem("<Seleccione Reserva>");
        for (Reserva reserva : resData.buscarReservaPorFecha(AdministracionView.FECHA)) {
            comboBoxNumeroReserva.addItem("" + reserva.getIdReserva());
        }
    }

    private void limpiarCampos() {
        if(comboBoxNumeroReserva.getItemCount()!=0){
        comboBoxNumeroReserva.setSelectedIndex(0);
        }
        textFieldNumeroHab.setText("");
        textFieldPisoHab.setText("");
        textFieldTipoHab.setText("");
        textFieldNombre.setText("");
        textFieldDni.setText("");
        textFieldEmail.setText("");
        textFieldTelefono.setText("");
        textFieldDomicilio.setText("");
        textFieldFechaIn.setText("");
        textFieldFechaOut.setText("");
        textFieldValor.setText("");
        botonGuardar.setEnabled(false);
    }

    private void cargarDatosHabitacion() {
        habitacion = reserva.getHabitacion();
        textFieldNumeroHab.setText(habitacion.getIdHabitacion() + "");
        textFieldPisoHab.setText(habitacion.getPiso() + "");
        textFieldTipoHab.setText(habitacion.getTipoHabitacion().name());
    }

    private void cargarDatosHuesped() {
        huesped = reserva.getHuesped();
        textFieldNombre.setText(huesped.getNombre());
        textFieldDni.setText(huesped.getDni() + "");
        textFieldEmail.setText(huesped.getCorreo());
        textFieldTelefono.setText(huesped.getCelular());
        textFieldDomicilio.setText(huesped.getDomicilio());
    }

    private void cargarDatosReserva() {
        comboBoxNumeroReserva.setSelectedItem("" + reserva.getIdReserva());
        if (reserva.getFechaInn().equals(AdministracionView.FECHA)) {
            labelChekIn.setText("CHECK IN");
        } else if (reserva.getFechaOut().equals(AdministracionView.FECHA)) {
            labelChekIn.setText("CHECK OUT");
        }
        textFieldFechaIn.setText(reserva.getFechaInn().toString());
        textFieldFechaOut.setText(reserva.getFechaOut().toString());
        textFieldValor.setText(reserva.getImporte() + "");
    }
}
