/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasInfo;

import java.awt.Color;
import VistasInfo.SimpleExt;

/**
 *
 * @author joelb
 */
public class Galeria extends javax.swing.JInternalFrame {

    /**
     * Creates new form Galeria
     */
    public Galeria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(27, 118, 134));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(176, 184, 157));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 60));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GALERIA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 10, 150, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 60);

        jPanel4.setBackground(new java.awt.Color(176, 184, 157));
        jPanel4.setPreferredSize(new java.awt.Dimension(1020, 60));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EL HOTEL");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 150, 40);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(140, 70, 150, 40);

        jPanel8.setBackground(new java.awt.Color(176, 184, 157));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAS HABITACIONES");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(0, 0, 270, 40);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(290, 70, 270, 40);

        jPanel9.setBackground(new java.awt.Color(176, 184, 157));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SPA");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel9);
        jPanel9.setBounds(560, 70, 90, 40);

        jPanel10.setBackground(new java.awt.Color(176, 184, 157));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GASTRONOMIA");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel10);
        jPanel10.setBounds(650, 70, 210, 40);

        jPanel16.setBackground(new java.awt.Color(27, 118, 134));
        jPanel2.add(jPanel16);
        jPanel16.setBounds(0, 60, 140, 60);

        jPanel17.setBackground(new java.awt.Color(27, 118, 134));
        jPanel2.add(jPanel17);
        jPanel17.setBounds(860, 70, 160, 50);

        jPanel14.setBackground(new java.awt.Color(27, 118, 134));
        jPanel14.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spa4.png"))); // NOI18N
        jPanel14.add(jLabel14);
        jLabel14.setBounds(520, 290, 460, 255);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spa1.png"))); // NOI18N
        jPanel14.add(jLabel15);
        jLabel15.setBounds(40, 20, 460, 255);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spa2.png"))); // NOI18N
        jPanel14.add(jLabel16);
        jLabel16.setBounds(520, 20, 460, 255);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spa3.png"))); // NOI18N
        jPanel14.add(jLabel17);
        jLabel17.setBounds(40, 290, 460, 255);

        jTabbedPane2.addTab("0", jPanel14);

        jPanel15.setBackground(new java.awt.Color(27, 118, 134));
        jPanel15.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gastronimia4.png"))); // NOI18N
        jPanel15.add(jLabel10);
        jLabel10.setBounds(520, 290, 460, 255);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gastronimia1.png"))); // NOI18N
        jPanel15.add(jLabel11);
        jLabel11.setBounds(40, 20, 460, 255);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gastronimia2.png"))); // NOI18N
        jPanel15.add(jLabel12);
        jLabel12.setBounds(520, 20, 460, 255);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gastronimia3.png"))); // NOI18N
        jPanel15.add(jLabel13);
        jLabel13.setBounds(40, 290, 460, 255);

        jTabbedPane2.addTab("1", jPanel15);

        jPanel12.setBackground(new java.awt.Color(27, 118, 134));
        jPanel12.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel5.png"))); // NOI18N
        jPanel12.add(jLabel6);
        jLabel6.setBounds(530, 290, 460, 255);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel1.png"))); // NOI18N
        jPanel12.add(jLabel7);
        jLabel7.setBounds(50, 20, 460, 255);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel2.png"))); // NOI18N
        jPanel12.add(jLabel8);
        jLabel8.setBounds(530, 20, 460, 255);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel4.png"))); // NOI18N
        jPanel12.add(jLabel9);
        jLabel9.setBounds(50, 290, 460, 255);

        jTabbedPane2.addTab("2", jPanel12);

        jPanel13.setBackground(new java.awt.Color(27, 118, 134));
        jPanel13.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(176, 184, 157));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Simple");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(0, 0, 60, 30);

        jPanel13.add(jPanel3);
        jPanel3.setBounds(0, 20, 60, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Simple Queen");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(0, 0, 110, 30);

        jPanel13.add(jPanel5);
        jPanel5.setBounds(60, 20, 110, 30);

        jPanel6.setBackground(new java.awt.Color(176, 184, 157));
        jPanel6.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Doble Tween");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(0, 0, 110, 30);

        jPanel13.add(jPanel6);
        jPanel6.setBounds(170, 20, 110, 30);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Doble Matrimonial");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(0, 0, 140, 30);

        jPanel13.add(jPanel7);
        jPanel7.setBounds(280, 20, 140, 30);

        jPanel18.setBackground(new java.awt.Color(176, 184, 157));
        jPanel18.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Triple Tween");
        jPanel18.add(jLabel23);
        jLabel23.setBounds(0, 0, 100, 30);

        jPanel13.add(jPanel18);
        jPanel18.setBounds(420, 20, 100, 30);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Triple Matrimonial");
        jPanel19.add(jLabel19);
        jLabel19.setBounds(0, 0, 140, 30);

        jPanel13.add(jPanel19);
        jPanel19.setBounds(520, 20, 140, 30);

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel20MouseExited(evt);
            }
        });
        jPanel20.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(176, 184, 157));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SUITE DE LUJO");
        jPanel20.add(jLabel22);
        jLabel22.setBounds(0, 0, 160, 30);

        jPanel13.add(jPanel20);
        jPanel20.setBounds(660, 20, 160, 30);

        jTabbedPane2.addTab("3", jPanel13);

        jPanel2.add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 80, 1020, 620);
        jTabbedPane2.getAccessibleContext().setAccessibleName("3");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1020, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(176,184,157));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(176,184,157));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(176,184,157));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(176,184,157));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseEntered
        // TODO add your handling code here:
        jPanel20.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel20MouseEntered

    private void jPanel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseExited
        // TODO add your handling code here:
        jPanel20.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel20MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
//        SimpleExt simpleExt = new SimpleExt();
//        jPanel11.add(simpleExt.mostrarPanel());
//        jPanel11.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
