
package layout;


public class VentanaBorder extends javax.swing.JFrame {
private boolean menuActivo = true;
private int posicionPanelIconos;
    public VentanaBorder() {
      
        initComponents();
        posicionPanelIconos = panelIconos.getX();
        this.setSize(800,600);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        panelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelOeste = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelIconos = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNorte.setBackground(new java.awt.Color(0, 204, 204));
        panelNorte.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU1");
        jLabel1.setPreferredSize(new java.awt.Dimension(63, 50));
        panelNorte.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU2");
        jLabel2.setPreferredSize(new java.awt.Dimension(63, 50));
        panelNorte.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU3");
        jLabel3.setPreferredSize(new java.awt.Dimension(63, 50));
        panelNorte.add(jLabel3);

        getContentPane().add(panelNorte, java.awt.BorderLayout.NORTH);

        panelSur.setLayout(new java.awt.GridLayout(1, 3));

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FOOTER CON DATOS DEL HOTEL");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(391, 60));
        panelSur.add(jLabel4);

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelOeste.setBackground(new java.awt.Color(204, 204, 204));
        panelOeste.setLayout(new java.awt.GridLayout());

        panelBotones.setLayout(new java.awt.GridLayout(6, 1));
        panelBotones.add(jLabel10);

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("ADMINISTRACION");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setPreferredSize(new java.awt.Dimension(150, 28));
        panelBotones.add(jButton6);

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("HUESPED");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(150, 28));
        panelBotones.add(jButton5);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("INFORMACION");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(150, 28));
        panelBotones.add(jButton4);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("HABITACIONES");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPreferredSize(new java.awt.Dimension(150, 28));
        panelBotones.add(jButton2);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("RESERVAS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(150, 28));
        panelBotones.add(jButton1);

        panelOeste.add(panelBotones);

        panelIconos.setPreferredSize(new java.awt.Dimension(162, 30));
        panelIconos.setLayout(new java.awt.GridLayout(6, 1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelIconos.add(jButton7);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/concierge.png"))); // NOI18N
        panelIconos.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/person.png"))); // NOI18N
        panelIconos.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        panelIconos.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/king_bed.png"))); // NOI18N
        panelIconos.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book_online.png"))); // NOI18N
        panelIconos.add(jLabel9);

        panelOeste.add(panelIconos);

        getContentPane().add(panelOeste, java.awt.BorderLayout.WEST);

        panelCentro.setBackground(new java.awt.Color(204, 204, 255));
        panelCentro.setLayout(null);
        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(menuActivo){
           panelOeste.remove(panelBotones);
           posicionPanelIconos = panelIconos.getX();
           panelIconos.setLocation(0, panelIconos.getY());
           panelCentro.setSize(panelCentro.getWidth()+100, panelCentro.getHeight());
           menuActivo = false;
           panelOeste.setSize(panelOeste.getWidth()/2, panelOeste.getHeight());
           
       } else {
           
           panelOeste.setSize(panelOeste.getWidth()*2, panelOeste.getHeight());
           panelIconos.setLocation(posicionPanelIconos, panelIconos.getY());
           panelOeste.add(panelBotones);
           menuActivo = true;
       }
       this.repaint();
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelIconos;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelOeste;
    private javax.swing.JPanel panelSur;
    // End of variables declaration//GEN-END:variables

}
